# We start from an Ubuntu image with CUDA installed
#FROM nvidia/cuda:11.0.3-base-ubuntu18.04
#FROM nvidia/cuda:12.0.1-base-ubuntu22.04
# Use cudagl image
FROM pytorch/pytorch:1.13.1-cuda11.6-cudnn8-devel

#ENV DEBIAN_FRONTEND=noninteractive


# Install the requirements
RUN /bin/bash -c ". /opt/conda/etc/profile.d/conda.sh && \
    pip install setuptools==57.0.0 && \
    pip install diffusers --upgrade && \
    pip install opencv-python && \
    conda install lightning -c conda-forge && \
    conda install -c conda-forge matplotlib && \
    conda install -c conda-forge torchvision==0.14.1 && \
    conda install zarr && \
    conda install numpy -y && \
    conda install -c anaconda ipykernel && \
    pip install scikit-image==0.19.3 scikit-video==1.1.11 \ 
    zarr==2.12.0 numcodecs==0.10.2 \
    pygame==2.1.2 pymunk==6.2.1 gym==0.21.0 shapely==1.8.4  &&\
    pip install gdown \
    pip install wandb"

RUN apt-get update && apt-get install ffmpeg libsm6 libxext6  -y

ENV WANDB_API_KEY=f6f588f4cef675acd3eae76728c5cfcca8e7026b